//
// Created by kernel-dbg on 24-3-2.
//

#ifndef ZEUSNET_KERNEL_LIR_OPTION_FIELD_MEAN_H
#define ZEUSNET_KERNEL_LIR_OPTION_FIELD_MEAN_H
#define OPTION_START_INDEX 3
#define OPTION_LARGEST_INDEX 40
#endif // ZEUSNET_KERNEL_LIR_OPTION_FIELD_MEAN_H
