//
// Created by kernel-dbg on 24-2-28.
//

#ifndef ZEUSNET_KERNEL_LIR_CONFIGURATION_H
#define ZEUSNET_KERNEL_LIR_CONFIGURATION_H
#define LIR_TOS_VALUE 10
#define BITS_PER_BYTE 8
#define MAX_INTERFACE_COUNT 4
#define MAXIMUM_SUPPORTED_HOOK_FUNCTIONS 20
#define LIR_TTL 64
#define LIR_MTU 1500
#define LIR_MSS 1460
#define LIR_VERSION_NUMBER 5
#endif // ZEUSNET_KERNEL_LIR_CONFIGURATION_H
